"""PDF Export — generates professionally formatted PDF reports.

Feature 6: Replace plain txt download with formatted PDF.
Uses reportlab for rendering.
"""

import logging
from datetime import datetime
from typing import Optional
from io import BytesIO

logger = logging.getLogger(__name__)

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm, mm
    from reportlab.lib.colors import HexColor
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, HRFlowable,
    )
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("reportlab not installed. PDF export disabled. Run: pip install reportlab")


# Color palette
PURPLE = HexColor("#667eea") if REPORTLAB_AVAILABLE else None
DARK_BG = HexColor("#1a1a2e") if REPORTLAB_AVAILABLE else None
GREEN = HexColor("#11998e") if REPORTLAB_AVAILABLE else None
RED = HexColor("#eb3349") if REPORTLAB_AVAILABLE else None
ORANGE = HexColor("#f7971e") if REPORTLAB_AVAILABLE else None
YELLOW = HexColor("#ffd200") if REPORTLAB_AVAILABLE else None
GREY = HexColor("#666666") if REPORTLAB_AVAILABLE else None
WHITE = HexColor("#FFFFFF") if REPORTLAB_AVAILABLE else None
BLACK = HexColor("#000000") if REPORTLAB_AVAILABLE else None
LIGHT_GREY = HexColor("#F0F0F0") if REPORTLAB_AVAILABLE else None


def _get_styles():
    """Build custom paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontSize=28,
        textColor=PURPLE,
        spaceAfter=12,
        alignment=TA_CENTER,
    ))

    styles.add(ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontSize=14,
        textColor=GREY,
        alignment=TA_CENTER,
        spaceAfter=30,
    ))

    styles.add(ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=16,
        textColor=PURPLE,
        spaceBefore=18,
        spaceAfter=8,
        borderPadding=(0, 0, 4, 0),
    ))

    styles.add(ParagraphStyle(
        "BodyText2",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        textColor=BLACK,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        "FooterStyle",
        parent=styles["Normal"],
        fontSize=8,
        textColor=GREY,
        alignment=TA_CENTER,
    ))

    styles.add(ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=RED,
        alignment=TA_CENTER,
        spaceBefore=20,
    ))

    return styles


def _add_footer(canvas, doc):
    """Add footer to every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(GREY)
    footer_text = "Generated by Legal AI Platform | For informational purposes only"
    canvas.drawCentredString(A4[0] / 2, 20 * mm, footer_text)
    canvas.drawRightString(A4[0] - 2 * cm, 20 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _risk_color(level: str):
    """Return color for a risk level string."""
    level_lower = level.lower() if level else ""
    if "critical" in level_lower:
        return RED
    elif "high" in level_lower:
        return ORANGE
    elif "medium" in level_lower or "moderate" in level_lower:
        return YELLOW
    else:
        return GREEN


def generate_analysis_report(result: dict, filename: str = "analysis_report.pdf") -> bytes:
    """Generate a professionally formatted PDF analysis report.

    Args:
        result: The analysis result dict from run_full_analysis().
        filename: Output filename (for metadata only).

    Returns:
        PDF file as bytes.
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=3 * cm,
    )

    styles = _get_styles()
    elements = []

    # ── Cover Page ──
    elements.append(Spacer(1, 4 * cm))
    elements.append(Paragraph("⚖️ Legal Document Analysis Report", styles["CoverTitle"]))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["CoverSubtitle"],
    ))

    # Risk badge
    is_legal = result.get("is_legal", False)
    conf = result.get("legal_confidence", 0)
    status = "Legal Document" if is_legal else "Not a Legal Document"
    elements.append(Paragraph(
        f"<b>Status:</b> {status} | <b>Confidence:</b> {int(conf * 100)}%",
        styles["CoverSubtitle"],
    ))

    proc_ms = result.get("processing_time_ms", 0)
    if proc_ms:
        elements.append(Paragraph(
            f"Processing Time: {proc_ms / 1000:.1f}s | Chunks: {result.get('chunk_count', 0)}",
            styles["CoverSubtitle"],
        ))

    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "⚠️ This report is for informational purposes only. Always consult a legal professional.",
        styles["Disclaimer"],
    ))

    elements.append(PageBreak())

    # ── Simplified Version ──
    simplified = result.get("simplified_text", "")
    if simplified and not simplified.startswith("["):
        elements.append(Paragraph("✨ Simplified Version", styles["SectionHeading"]))
        elements.append(HRFlowable(width="100%", color=PURPLE, thickness=1))
        elements.append(Spacer(1, 0.3 * cm))

        for para in simplified.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            # Handle markdown headings
            if para.startswith("##"):
                clean = para.lstrip("#").strip()
                elements.append(Paragraph(f"<b>{clean}</b>", styles["SectionHeading"]))
            elif para.startswith("- ") or para.startswith("* "):
                # Bullet points
                for line in para.split("\n"):
                    line = line.lstrip("- *").strip()
                    if line:
                        elements.append(Paragraph(f"• {line}", styles["BodyText2"]))
            else:
                # Escape XML special chars for reportlab
                safe = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                elements.append(Paragraph(safe, styles["BodyText2"]))

        elements.append(PageBreak())

    # ── Risk Analysis ──
    risk = result.get("risk_analysis", "")
    if risk and not risk.startswith("["):
        elements.append(Paragraph("⚠️ Risk Analysis", styles["SectionHeading"]))
        elements.append(HRFlowable(width="100%", color=RED, thickness=1))
        elements.append(Spacer(1, 0.3 * cm))

        for para in risk.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("##"):
                clean = para.lstrip("#").strip()
                elements.append(Paragraph(f"<b>{clean}</b>", styles["SectionHeading"]))
            elif para.startswith("- ") or para.startswith("* "):
                for line in para.split("\n"):
                    line = line.lstrip("- *").strip()
                    if line:
                        elements.append(Paragraph(f"• {line}", styles["BodyText2"]))
            else:
                safe = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                elements.append(Paragraph(safe, styles["BodyText2"]))

        elements.append(PageBreak())

    # ── Detected Legal Terms ──
    terms = result.get("detected_terms", [])
    if terms:
        elements.append(Paragraph("🏷️ Detected Legal Terms", styles["SectionHeading"]))
        elements.append(HRFlowable(width="100%", color=PURPLE, thickness=1))
        elements.append(Spacer(1, 0.3 * cm))

        # Build a 3-column table
        cols = 3
        rows = []
        row = []
        for term in terms:
            row.append(term)
            if len(row) == cols:
                rows.append(row)
                row = []
        if row:
            while len(row) < cols:
                row.append("")
            rows.append(row)

        if rows:
            table = Table(rows, colWidths=[5.5 * cm] * cols)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GREY),
                ("TEXTCOLOR", (0, 0), (-1, -1), BLACK),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, GREY),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            elements.append(table)

    # ── Footer disclaimer ──
    elements.append(Spacer(1, 2 * cm))
    elements.append(Paragraph(
        "⚖️ Generated by Legal AI Platform | For informational purposes only. "
        "Always consult a qualified legal professional.",
        styles["Disclaimer"],
    ))

    doc.build(elements, onFirstPage=_add_footer, onLaterPages=_add_footer)
    return buffer.getvalue()


def generate_case_report(case_result: dict, filename: str = "case_report.pdf") -> bytes:
    """Generate a PDF report for case research results.

    Args:
        case_result: Result dict from run_case_research().
        filename: Output filename (for metadata only).

    Returns:
        PDF file as bytes.
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=3 * cm,
    )

    styles = _get_styles()
    elements = []

    # ── Cover ──
    elements.append(Spacer(1, 4 * cm))
    elements.append(Paragraph("🔍 Legal Case Research Report", styles["CoverTitle"]))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["CoverSubtitle"],
    ))

    sections_found = case_result.get("case_sections_found", 0)
    proc_ms = case_result.get("processing_time_ms", 0)
    elements.append(Paragraph(
        f"Applicable Sections Found: {sections_found} | Processing: {proc_ms / 1000:.1f}s",
        styles["CoverSubtitle"],
    ))

    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "⚠️ This report is for informational purposes only. Always consult a legal professional.",
        styles["Disclaimer"],
    ))

    elements.append(PageBreak())

    # ── Applicable Law Sections Table ──
    retrieved_laws = case_result.get("retrieved_laws", [])
    if retrieved_laws:
        elements.append(Paragraph("📜 Applicable Law Sections", styles["SectionHeading"]))
        elements.append(HRFlowable(width="100%", color=PURPLE, thickness=1))
        elements.append(Spacer(1, 0.3 * cm))

        header = ["Section", "Act", "Crime", "Punishment", "Bailable"]
        data = [header]
        for law in retrieved_laws:
            data.append([
                str(law.get("section", "N/A")),
                str(law.get("act_name", "N/A"))[:20],
                str(law.get("crime", "N/A"))[:30],
                str(law.get("punishment", "N/A"))[:30],
                str(law.get("bailable", "N/A")),
            ])

        table = Table(data, colWidths=[2 * cm, 3.5 * cm, 4.5 * cm, 4.5 * cm, 2 * cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PURPLE),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GREY),
            ("GRID", (0, 0), (-1, -1), 0.5, GREY),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(table)
        elements.append(PageBreak())

    # ── AI Analysis ──
    analysis = case_result.get("case_analysis", "")
    if analysis and not analysis.startswith("["):
        elements.append(Paragraph("🧠 AI Legal Analysis", styles["SectionHeading"]))
        elements.append(HRFlowable(width="100%", color=PURPLE, thickness=1))
        elements.append(Spacer(1, 0.3 * cm))

        for para in analysis.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("##"):
                clean = para.lstrip("#").strip()
                elements.append(Paragraph(f"<b>{clean}</b>", styles["SectionHeading"]))
            elif para.startswith("- ") or para.startswith("* "):
                for line in para.split("\n"):
                    line = line.lstrip("- *").strip()
                    if line:
                        elements.append(Paragraph(f"• {line}", styles["BodyText2"]))
            else:
                safe = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                elements.append(Paragraph(safe, styles["BodyText2"]))

    # Footer
    elements.append(Spacer(1, 2 * cm))
    elements.append(Paragraph(
        "⚖️ Generated by Legal AI Platform | For informational purposes only.",
        styles["Disclaimer"],
    ))

    doc.build(elements, onFirstPage=_add_footer, onLaterPages=_add_footer)
    return buffer.getvalue()
